# Generated by Django 6.0.5 on 2026-06-10 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('Book', 'Book'), ('Article', 'Article'), ('Video', 'Video')], default='Book', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters', models.JSONField()),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='thematics.material')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='thematics.material')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('time_duration', models.DurationField()),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='thematics.material')),
            ],
        ),
        migrations.CreateModel(
            name='Thematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('quiz_count', models.SmallIntegerField()),
                ('flashcards_count', models.SmallIntegerField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thematics', to='thematics.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('questions_count', models.SmallIntegerField()),
                ('questions', models.JSONField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('HARD', 'Hard')], default='Medium', max_length=10)),
                ('thematics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='thematics.thematic')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('thematics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='thematics.thematic')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cards_count', models.SmallIntegerField()),
                ('cards', models.JSONField()),
                ('thematics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='thematics.thematic')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=5)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='thematics.discipline')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('discipline', 'language'), name='unique_discipline_translation')],
            },
        ),
        migrations.CreateModel(
            name='MaterialCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_material_links', to='thematics.collection')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_collection_links', to='thematics.material')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('material', 'collection'), name='unique_material_collection')],
            },
        ),
        migrations.CreateModel(
            name='MaterialDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_material_links', to='thematics.discipline')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_discipline_links', to='thematics.material')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('material', 'discipline'), name='unique_material_discipline')],
            },
        ),
    ]
